baseURL = "https://pariskomm.uz/"
# [en, zh-cn, fr, pl, ...] determines default content language
# [en, zh-cn, fr, pl, ...] 设置默认的语言
defaultContentLanguage = "ru"
# theme
# 主题
#theme = "DoIt"
# themes directory
# 主题目录
#themesDir = "../.."
publishDir = "docs"

# website title
# 网站标题
title = "ParisKomm.uz"

# whether to use robots.txt
# 是否使用 robots.txt
enableRobotsTXT = true
# whether to use git commit log
# 是否使用 git 信息
enableGitInfo = false
# whether to use emoji code
# 是否使用 emoji 代码
enableEmoji = true

# ignore some build errors
# 忽略一些构建错误
# ignoreErrors = ["error-remote-getjson", "error-missing-instagram-accesstoken"]

[module]

  [[module.imports]]
    path = "github.com/HEIGE-PCloud/DoIt"
    disable=false
